blank_issues_enabled: false
contact_links:
  - name: Something else? Message us on Discord :)
    url: https://discord.gg/vapESyrFmJ
    about: Join our Discord to ask questions, share thoughts, and more!
